# Dependency Review Action Configuration
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review

# Fail if any dependencies have vulnerabilities with this severity or higher
fail-on-severity: moderate

# Fail if any dependencies have these license issues
fail-on-scopes:
  - runtime
  - development

# Allow specific licenses (common open source licenses for PHP/Laravel ecosystem)
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - GPL-2.0
  - GPL-3.0
  - LGPL-2.1
  - LGPL-3.0

# Deny specific licenses (example - uncomment and modify as needed)
# deny-licenses:
#   - GPL-3.0-only
#   - AGPL-3.0

# Allow specific packages even if they have vulnerabilities (use sparingly)
allow-dependencies-licenses:
  # - package-name: "example/package"
  #   licenses: ["MIT", "Apache-2.0"]

# Custom comment for pull requests
comment-summary-in-pr: true

# Whether to retry on API failures
retry-on-snapshot-warnings: true

# Number of retries
retry-on-snapshot-warnings-timeout: 120

# Base branch for comparison (defaults to the PR target branch)
# base-ref: main

# Head branch for comparison (defaults to the PR source branch)  
# head-ref: feature-branch